{% set version = "0.12.0" %}

package:
  name: dipy
  version: {{ version }}

source:
  fn: dipy-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/04/dd/08f9a35a8351d32c1f659821dd72c0549954c126a3d68cc17002ae1dff07/dipy-{{ version }}.tar.gz
  md5: 72a1d734f7b9545fac46e720e157ac79

build:
    number: 1
    script: python setup.py install

requirements:
  build:
    - python
    - numpy x.x
    - nibabel
    - cython
    - gcc  # [not win]
  run:
    - python
    - numpy x.x
    - scipy
    - nibabel
    - scikit-learn
    - matplotlib
    - cvxopt  # [not win]
    - pytables
    - libgcc  # [not win]
    - vtk  # [py27]
test:
  imports:
    - dipy

about:
  home: https://nipy.org/dipy
  license:  3-clause BSD
  license_file: LICENSE
  summary: Diffusion MR Imaging in Python

extra:
  recipe-maintainers:
    - arokem
    - garyfallidis
